export const censusTemplateYears = [
  "1790",
  "1800",
  "1810",
  "1820",
  "1830",
  "1840",
  "1850",
  "1860",
  "1870",
  "1880",
  "1890",
  "1900",
  "1910",
  "1920",
  "1930",
  "1940",
  "1950",
];

export const censusTemplates = [
  {
    id: "us-census-1790",
    year: "1790",
    label: "1790 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1790 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "givenName", label: "Given Name" },
      { key: "surname", label: "Surname" },
      { key: "freeWhiteMales16Plus", label: "Free white males 16+" },
      { key: "freeWhiteMalesUnder16", label: "Free white males under 16" },
      { key: "freeWhiteFemales", label: "Free white females" },
      { key: "allOtherFreePersons", label: "All other free Persons" },
      { key: "slaves", label: "Slaves" },
      { key: "total", label: "TOTAL" },
    ],
  },
  {
    id: "us-census-1800",
    year: "1800",
    label: "1800 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1800 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "freeWhiteMalesUnder10", label: "Free White Persons - Males Under 10" },
      { key: "freeWhiteMales10To15", label: "Free White Persons - Males 10 to 15" },
      { key: "freeWhiteMales16To25", label: "Free White Persons - Males 16 to 25" },
      { key: "freeWhiteMales26To44", label: "Free White Persons - Males 26 to 44" },
      { key: "freeWhiteMalesOver45", label: "Free White Persons - Males Over 45" },
      { key: "freeWhiteFemalesUnder10", label: "Free White Persons - Females Under 10" },
      { key: "freeWhiteFemales10To15", label: "Free White Persons - Females 10 to 15" },
      { key: "freeWhiteFemales16To25", label: "Free White Persons - Females 16 to 25" },
      { key: "freeWhiteFemales26To44", label: "Free White Persons - Females 26 to 44" },
      { key: "freeWhiteFemalesOver45", label: "Free White Persons - Females Over 45" },
      { key: "total", label: "TOTAL" },
    ],
  },
  {
    id: "us-census-1810",
    year: "1810",
    label: "1810 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1810 United States Federal Census fields.",
    topInfo: [
      "1810 United States Federal Census",
      "National Archives and Records Administration© 1997-2021 Ancestry.com",
    ],
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "freeWhiteMalesUnder10", label: "Free White Persons - Males Under 10" },
      { key: "freeWhiteMales10To15", label: "Free White Persons - Males 10 to 15" },
      { key: "freeWhiteMales16To25", label: "Free White Persons - Males 16 to 25" },
      { key: "freeWhiteMales26To44", label: "Free White Persons - Males 26 to 44" },
      { key: "freeWhiteMalesOver45", label: "Free White Persons - Males Over 45" },
      { key: "freeWhiteFemalesUnder10", label: "Free White Persons - Females Under 10" },
      { key: "freeWhiteFemales10To15", label: "Free White Persons - Females 10 to 15" },
      { key: "freeWhiteFemales16To25", label: "Free White Persons - Females 16 to 25" },
      { key: "freeWhiteFemales26To44", label: "Free White Persons - Females 26 to 44" },
      { key: "freeWhiteFemalesOver45", label: "Free White Persons - Females Over 45" },
      { key: "total", label: "TOTAL" },
    ],
  },
  {
    id: "us-census-1820",
    year: "1820",
    label: "1820 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1820 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "county", label: "County" },
      { key: "state", label: "State" },
      { key: "engagedInAgriculture", label: "# Engaged in Agriculture" },
      { key: "freeWhiteMalesUnder10", label: "Free White Persons - Males Under 10" },
      { key: "freeWhiteMales10To15", label: "Free White Persons - Males 10 to 15" },
      { key: "freeWhiteMales16To25", label: "Free White Persons - Males 16 to 25" },
      { key: "freeWhiteMales26To44", label: "Free White Persons - Males 26 to 44" },
      { key: "freeWhiteMalesOver45", label: "Free White Persons - Males Over 45" },
      { key: "freeWhiteFemalesUnder10", label: "Free White Persons - Females Under 10" },
      { key: "freeWhiteFemales10To15", label: "Free White Persons - Females 10 to 15" },
      { key: "freeWhiteFemales16To25", label: "Free White Persons - Females 16 to 25" },
      { key: "freeWhiteFemales26To44", label: "Free White Persons - Females 26 to 44" },
      { key: "freeWhiteFemalesOver45", label: "Free White Persons - Females Over 45" },
    ],
  },
  {
    id: "us-census-1830",
    year: "1830",
    label: "1830 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1830 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "totalFreeWhitePersons", label: "Total Free White Persons" },
      { key: "totalSlaves", label: "Total Slaves" },
      { key: "freeWhiteMalesUnder5", label: "Males Under 5" },
      { key: "freeWhiteMales5To9", label: "Males 5 to under 10" },
      { key: "freeWhiteMales10To14", label: "Males 10 to under 15" },
      { key: "freeWhiteMales15To19", label: "Males 15 to under 20" },
      { key: "freeWhiteMales20To29", label: "Males 20 to under 30" },
      { key: "freeWhiteMales30To39", label: "Males 30 to under 40" },
      { key: "freeWhiteMales40To49", label: "Males 40 to under 50" },
      { key: "freeWhiteMales50To59", label: "Males 50 to under 60" },
      { key: "freeWhiteMales60To69", label: "Males 60 to under 70" },
      { key: "freeWhiteMales70To79", label: "Males 70 to under 80" },
      { key: "freeWhiteMales80To89", label: "Males 80 to under 90" },
      { key: "freeWhiteMales90To99", label: "Males 90 to under 100" },
      { key: "freeWhiteMales100Plus", label: "Males 100+" },
      { key: "freeWhiteFemalesUnder5", label: "Females Under 5" },
      { key: "freeWhiteFemales5To9", label: "Females 5 to under 10" },
      { key: "freeWhiteFemales10To14", label: "Females 10 to under 15" },
      { key: "freeWhiteFemales15To19", label: "Females 15 to under 20" },
      { key: "freeWhiteFemales20To29", label: "Females 20 to under 30" },
      { key: "freeWhiteFemales30To39", label: "Females 30 to under 40" },
      { key: "freeWhiteFemales40To49", label: "Females 40 to under 50" },
      { key: "freeWhiteFemales50To59", label: "Females 50 to under 60" },
      { key: "freeWhiteFemales60To69", label: "Females 60 to under 70" },
      { key: "freeWhiteFemales70To79", label: "Females 70 to under 80" },
      { key: "freeWhiteFemales80To89", label: "Females 80 to under 90" },
      { key: "freeWhiteFemales90To99", label: "Females 90 to under 100" },
      { key: "freeWhiteFemales100Plus", label: "Females 100+" },
      { key: "slaveFemalesUnder5", label: "Slaves - Female Under 5" },
      { key: "slaveFemales5To9", label: "Slaves - Female 5 to under 10" },
      { key: "slaveFemales10To14", label: "Slaves - Female 10 to under 15" },
      { key: "slaveFemales15To19", label: "Slaves - Female 15 to under 20" },
      { key: "slaveFemales20To29", label: "Slaves - Female 20 to under 30" },
      { key: "slaveFemales30To39", label: "Slaves - Female 30 to under 40" },
      { key: "slaveFemales40To49", label: "Slaves - Female 40 to under 50" },
      { key: "slaveFemales50To59", label: "Slaves - Female 50 to under 60" },
      { key: "slaveFemales60To69", label: "Slaves - Female 60 to under 70" },
      { key: "slaveFemales70To79", label: "Slaves - Female 70 to under 80" },
      { key: "slaveFemales80To89", label: "Slaves - Female 80 to under 90" },
      { key: "slaveFemales90To99", label: "Slaves - Female 90 to under 100" },
      { key: "slaveFemales100Plus", label: "Slaves - Female 100+" },
    ],
  },
  {
    id: "us-census-1840",
    year: "1840",
    label: "1840 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1840 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "name", label: "Name" },
      { key: "age", label: "Age" },
      { key: "city", label: "City" },
      { key: "malesUnder5", label: "Males Under 5" },
      { key: "malesUnder10", label: "Males under 10" },
      { key: "malesUnder15", label: "Males under 15" },
      { key: "malesUnder20", label: "Males under 20" },
      { key: "malesUnder30", label: "Males under 30" },
      { key: "malesUnder40", label: "Males under 40" },
      { key: "malesUnder50", label: "Males under 50" },
      { key: "malesUnder60", label: "Males under 60" },
      { key: "malesUnder70", label: "Males under 70" },
      { key: "malesUnder80", label: "Males under 80" },
      { key: "malesUnder90", label: "Males under 90" },
      { key: "malesUnder100", label: "Males under 100" },
      { key: "males100Plus", label: "Males 100+" },
      { key: "femalesUnder5", label: "Females Under 5" },
      { key: "femalesUnder10", label: "Females under 10" },
      { key: "femalesUnder15", label: "Females under 15" },
      { key: "femalesUnder20", label: "Females under 20" },
      { key: "femalesUnder30", label: "Females under 30" },
      { key: "femalesUnder40", label: "Females under 40" },
      { key: "femalesUnder50", label: "Females under 50" },
      { key: "femalesUnder60", label: "Females under 60" },
      { key: "femalesUnder70", label: "Females under 70" },
      { key: "femalesUnder80", label: "Females under 80" },
      { key: "femalesUnder90", label: "Females under 90" },
      { key: "femalesUnder100", label: "Females under 100" },
      { key: "females100Plus", label: "Females 100+" },
    ],
  },
  {
    id: "us-census-1850",
    year: "1850",
    label: "1850 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1850 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "age", label: "Age" },
      { key: "birthYear", label: "Birth Year" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "occupation", label: "Occupation" },
      { key: "industry", label: "Industry" },
      { key: "realEstate", label: "Real Estate" },
      { key: "birthPlace", label: "Birth Place" },
      { key: "marriedWithinTheYear", label: "Married within the Year" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "cannotReadWrite", label: "Cannot Read, Write" },
      { key: "condition", label: "Condition" },
    ],
  },
  {
    id: "us-census-1860",
    year: "1860",
    label: "1860 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1860 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "age", label: "Age" },
      { key: "birthYear", label: "Birth Year" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "occupation", label: "Occupation" },
      { key: "realEstateValue", label: "Real Estate Value" },
      { key: "personalEstateValue", label: "Personal Estate Value" },
      { key: "birthPlace", label: "Birth Place" },
      { key: "marriedWithinYear", label: "Married Within Year" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "cannotReadWrite", label: "Cannot Read, Write" },
      { key: "disabilityCondition", label: "Disability Condition" },
    ],
  },
  {
    id: "us-census-1870",
    year: "1870",
    label: "1870 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1870 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "age", label: "Age" },
      { key: "birthYear", label: "Birth Year" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "occupation", label: "Occupation" },
      { key: "realEstateValue", label: "Real Estate Value" },
      { key: "personalEstateValue", label: "Personal Estate Value" },
      { key: "birthplace", label: "Birthplace" },
      { key: "fatherForeignBirth", label: "Father of Foreign Birth" },
      { key: "motherForeignBirth", label: "Mother of Foreign Birth" },
      { key: "birthMonth", label: "Birth Month" },
      { key: "marriageMonth", label: "Marriage Month" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "cannotRead", label: "Cannot Read" },
      { key: "cannotWrite", label: "Cannot Write" },
      { key: "condition", label: "Condition" },
      { key: "maleCitizenOver21", label: "Male Citizen Over 21" },
      { key: "deniedVotingRights", label: "Denied Voting Rights" },
    ],
  },
  {
    id: "us-census-1880",
    year: "1880",
    label: "1880 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1880 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "street", label: "Street" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "race", label: "Race" },
      { key: "gender", label: "Gender" },
      { key: "age", label: "Age" },
      { key: "birthMonth", label: "Birth Month" },
      { key: "birthYear", label: "Birth Year" },
      { key: "relationToHeadOfHouse", label: "Relation to Head of House" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "marriedDuringCensusYear", label: "Married During Census Year" },
      { key: "occupation", label: "Occupation" },
      { key: "monthsNotEmployed", label: "Months Not Employed" },
      { key: "sick", label: "Sick" },
      { key: "blind", label: "Blind" },
      { key: "deafAndDumb", label: "Deaf and Dumb" },
      { key: "idiotic", label: "Idiotic" },
      { key: "insane", label: "Insane" },
      { key: "maimedCrippledBedridden", label: "Maimed, Crippled, or Bedridden" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "cannotRead", label: "Cannot Read" },
      { key: "cannotWrite", label: "Cannot Write" },
      { key: "birthplace", label: "Birthplace" },
      { key: "fathersBirthplace", label: "Father's Birthplace" },
      { key: "mothersBirthplace", label: "Mother's Birthplace" },
    ],
  },
  {
    id: "us-census-1890",
    year: "1890",
    label: "1890 U.S. Census",
    description: "Alternate-source worksheet for the mostly destroyed 1890 United States Federal Census.",
    note: "Most of the 1890 U.S. Federal Census was destroyed in a fire in January 1921 at the Department of Commerce building in Washington, D.C. About 25% of the records suffered damage in 1896, the 1921 fire destroyed or severely damaged roughly 99% of the remaining population schedules, and the few survivors were officially destroyed by 1935.\n\nGenealogists need to use alternate sources, such as:\nState censuses\nLand records\nCity Directories",
    noteLink: {
      prefix: "See ",
      label: "FamilySearch.org",
      url: "https://www.familysearch.org/en/search/collection/1610551",
      suffix: " for more information.",
    },
    columns: [
      { key: "inquiry", label: "Inquiry" },
      { key: "column1", label: "Column 1" },
      { key: "column2", label: "Column 2" },
      { key: "column3", label: "Column 3" },
      { key: "column4", label: "Column 4" },
    ],
    starterRows: [
      { inquiry: "Full Name", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Military Service", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Relationship", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Race", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Sex", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Age", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Marital Status", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Married in Year?", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Children (Born/Living)", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Place of Birth", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Father's Birthplace", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Mother's Birthplace", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Naturalized?", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Occupation", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Months Unemployed", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "School (Months)", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Able to Read", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Able to Write", column1: "", column2: "", column3: "", column4: "" },
      { inquiry: "Language Spoken", column1: "", column2: "", column3: "", column4: "" },
    ],
  },
  {
    id: "us-census-1900",
    year: "1900",
    label: "1900 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1900 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "street", label: "Street" },
      { key: "dwellingInOrderOfVisitation", label: "Number of Dwelling in Order of Visitation" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationship", label: "Relationship" },
      { key: "race", label: "Race" },
      { key: "gender", label: "Gender" },
      { key: "birthMonth", label: "Birth Month" },
      { key: "birthYear", label: "Birth Year" },
      { key: "age", label: "Age" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "yearsMarried", label: "Years Married" },
      { key: "numberOfChildrenBorn", label: "Number of Children Born" },
      { key: "numberOfChildrenLiving", label: "Number of Children Living" },
      { key: "birthplace", label: "Birthplace" },
      { key: "fathersBirthplace", label: "Father's Birthplace" },
      { key: "mothersBirthplace", label: "Mother's Birthplace" },
      { key: "immigrationYear", label: "Immigration Year" },
      { key: "yearsInUs", label: "Years in US" },
      { key: "naturalization", label: "Naturalization" },
      { key: "occupation", label: "Occupation" },
      { key: "monthsNotEmployed", label: "Months Not Employed" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "canRead", label: "Can Read" },
      { key: "canWrite", label: "Can Write" },
      { key: "canSpeakEnglish", label: "Can Speak English" },
      { key: "houseOwnedOrRented", label: "House Owned or Rented" },
      { key: "houseOwnedFreeOrMortgaged", label: "House Owned Free or Mortgaged" },
      { key: "farmOrHouse", label: "Farm or House" },
    ],
  },
  {
    id: "us-census-1910",
    year: "1910",
    label: "1910 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1910 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "streetName", label: "Street Name" },
      { key: "houseNumber", label: "House Number" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationship", label: "Relationship" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "age", label: "Age" },
      { key: "estimatedBirthYear", label: "Estimated Birth Year" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "numberYearsPresentMarriage", label: "Number Years of Present Marriage" },
      { key: "numberOfChildrenBorn", label: "Number of Children Born" },
      { key: "numberOfChildrenLiving", label: "Number of Children Living" },
      { key: "birthplace", label: "Birthplace" },
      { key: "fathersBirthplace", label: "Father's Birthplace" },
      { key: "mothersBirthplace", label: "Mother's Birthplace" },
      { key: "immigrationYear", label: "Immigration Year" },
      { key: "naturalizationStatus", label: "Naturalization Status" },
      { key: "selfNativeTongue", label: "Self Native Tongue" },
      { key: "occupation", label: "Occupation" },
      { key: "industry", label: "Industry" },
      { key: "selfEmployedOrNot", label: "Self Employed or Not" },
      { key: "numberOfWeeksOutOfWork", label: "Number of Weeks Out of Work" },
      { key: "canRead", label: "Can Read" },
      { key: "canWrite", label: "Can Write" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "ownOrRent", label: "Own or Rent" },
      { key: "homeOwned", label: "Home owned" },
      { key: "farmOrHouse", label: "Farm or House" },
      { key: "survivorOfConfederateOrUnionArmyOrNavy", label: "Survivor of Confederate or Union Army or Navy" },
      { key: "blind", label: "Blind" },
      { key: "deafAndDumb", label: "Deaf and Dumb" },
    ],
  },
  {
    id: "us-census-1920",
    year: "1920",
    label: "1920 U.S. Census",
    sourceWorkbook: "/templates/1920.xltx",
    description: "Spreadsheet-style entry form based on the 1920 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "street", label: "Street" },
      { key: "houseNumber", label: "House Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationship", label: "Relationship" },
      { key: "homeOwnedOrRented", label: "Home Owned or Rented" },
      { key: "homeFreeOrMortgaged", label: "Home Free or Mortgaged" },
      { key: "sex", label: "Sex" },
      { key: "race", label: "Race" },
      { key: "age", label: "Age" },
      { key: "estimatedBirthYear", label: "Estimated Birth Year" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "immigrationYear", label: "Immigration Year" },
      { key: "naturalizationStatus", label: "Naturalization Status" },
      { key: "naturalizationYear", label: "Naturalization Year" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "ableToRead", label: "Able to read" },
      { key: "ableToWrite", label: "Able to Write" },
      { key: "birthplace", label: "Birthplace" },
      { key: "nativeTongue", label: "Native Tongue" },
      { key: "fathersBirthplace", label: "Father's Birthplace" },
      { key: "mothersBirthplace", label: "Mother's Birthplace" },
    ],
  },
  {
    id: "us-census-1930",
    year: "1930",
    label: "1930 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1930 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "streetAddress", label: "Street Address" },
      { key: "houseNumber", label: "House Number" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationToHead", label: "Relation to Head" },
      { key: "homeOwnedOrRented", label: "Home Owned or Rented" },
      { key: "homeValue", label: "Home Value" },
      { key: "radioSet", label: "Radio Set" },
      { key: "livesOnFarm", label: "Lives on Farm" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "age", label: "Age" },
      { key: "estimatedBirthYear", label: "Estimated Birth Year" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "ageAtFirstMarriage", label: "Age at First Marriage" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "ableToReadAndWrite", label: "Able to Read and Write" },
      { key: "birthplace", label: "Birthplace" },
      { key: "fathersBirthplace", label: "Father's Birthplace" },
      { key: "mothersBirthplace", label: "Mother's Birthplace" },
      { key: "languageSpoken", label: "Language Spoken" },
      { key: "immigrationYear", label: "Immigration Year" },
      { key: "naturalization", label: "Naturalization" },
      { key: "ableToSpeakEnglish", label: "Able to Speak English" },
      { key: "occupation", label: "Occupation" },
      { key: "industry", label: "Industry" },
      { key: "classOfWorker", label: "Class of Worker" },
      { key: "employment", label: "Employment" },
      { key: "veteran", label: "Veteran" },
      { key: "war", label: "War" },
    ],
  },
  {
    id: "us-census-1940",
    year: "1940",
    label: "1940 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1940 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "line", label: "Line" },
      { key: "houseNumber", label: "House Number" },
      { key: "streetName", label: "Street Name" },
      { key: "houseOwnedOrRented", label: "House Owned or Rented" },
      { key: "valueOfHome", label: "Value of Home" },
      { key: "respondent", label: "Respondent" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationToHeadOfHouse", label: "Relation to Head of House" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "age", label: "Age" },
      { key: "estimatedBirthYear", label: "Estimated Birth Year" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "attendedSchoolOrCollege", label: "Attended School or College" },
      { key: "highestGradeCompleted", label: "Highest Grade Completed" },
      { key: "birthplace", label: "Birthplace" },
      { key: "citizenship", label: "Citizenship" },
      { key: "residenceCityIn1935", label: "Residence City in 1935" },
      { key: "residenceCountyIn1935", label: "Residence County in 1935" },
      { key: "residenceStateIn1935", label: "Residence State in 1935" },
      { key: "liveOnFarm", label: "Live on Farm" },
      { key: "publicEmergencyWork", label: "Public Emergency Work" },
      { key: "seekingWork", label: "Seeking Work" },
      { key: "employmentHistory", label: "Employment History" },
      { key: "employmentDetails", label: "Employment Details" },
      { key: "hoursWorkedWeekPriorToCensus", label: "Hours Worked Week Prior to Census" },
      { key: "durationOfUnemployment", label: "Duration Of Unemployment" },
      { key: "occupation", label: "Occupation" },
      { key: "industry", label: "Industry" },
      { key: "classOfWorker", label: "Class of Worker" },
      { key: "employmentCode", label: "Employment Code" },
      { key: "weeksWorkedIn1939", label: "Weeks Worked in 1939" },
      { key: "income", label: "Income" },
      { key: "incomeOtherSources", label: "Income Other Sources" },
      { key: "nameSupplemental", label: "Name (supplemental)" },
      { key: "fathersBirthPlace", label: "Father's Birth Place" },
      { key: "mothersBirthPlace", label: "Mother's Birth Place" },
      { key: "nativeLanguage", label: "Native Language" },
      { key: "veteran", label: "Veteran" },
      { key: "veteranFatherDead", label: "Veteran Father Dead" },
      { key: "militaryService", label: "Military Service" },
      { key: "usualOccupation", label: "Usual Occupation" },
      { key: "usualIndustry", label: "Usual Industry" },
      { key: "usualClassOfWorker", label: "Usual Class of Worker" },
      { key: "usualOccupationCode", label: "Usual Occupation Code" },
      { key: "womanMarriages", label: "Woman Marriages" },
      { key: "womanAgeAtFirstMarriage", label: "Woman Age at First Marriage" },
      { key: "numberOfChildren", label: "Number of Children" },
    ],
  },
  {
    id: "us-census-1950",
    year: "1950",
    label: "1950 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1950 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "line", label: "Line" },
      { key: "streetName", label: "Street Name" },
      { key: "houseApartmentNumber", label: "House Apt No" },
      { key: "dwellingNumber", label: "Dwelling #" },
      { key: "farm", label: "Farm" },
      { key: "acres", label: "Acres" },
      { key: "question1", label: "Question 1" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationToHeadOfHouse", label: "Relation to Head of House" },
      { key: "race", label: "Race" },
      { key: "gender", label: "Gender" },
      { key: "age", label: "Age" },
      { key: "birthMonth", label: "Birth Month" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "birthplace", label: "Birthplace" },
      { key: "naturalized", label: "Naturalized?" },
      { key: "citizenship", label: "Citizenship" },
      { key: "occupationLastWeek", label: "Occupation Last Week" },
      { key: "workedLastWeek", label: "Worked Last Week" },
      { key: "seekingWork", label: "Seeking Work" },
      { key: "employmentStatus", label: "Employment Status" },
      { key: "hoursWorked", label: "Hours Worked" },
      { key: "occupation", label: "Occupation" },
      { key: "industry", label: "Industry" },
      { key: "classOfWorker", label: "Class of Worker" },
      { key: "sameHouse", label: "Same House" },
      { key: "previouslyOnFarm", label: "Previously on Farm" },
      { key: "sameCounty", label: "Same County" },
      { key: "fatherBirthPlace", label: "Father Birth Place" },
      { key: "motherBirthPlace", label: "Mother Birth Place" },
      { key: "schoolCompleted", label: "School Completed" },
      { key: "gradeCompleted", label: "Grade Completed" },
      { key: "schoolAttendance", label: "School Attendance" },
      { key: "weeksWorked", label: "Weeks Worked" },
      { key: "wages", label: "Wages" },
      { key: "incomeLastYear", label: "Income Last Year" },
      { key: "supplementalIncome", label: "Supplemental Income" },
      { key: "worldWarIiVeteran", label: "World War II Veteran" },
      { key: "worldWarIVeteran", label: "World War I Veteran" },
      { key: "previousVeteran", label: "Previous Veteran" },
      { key: "previousOccupation", label: "Previous Occupation" },
      { key: "previousIndustry", label: "Previous Industry" },
      { key: "previousClassOfWorker", label: "Previous Class of Worker" },
      { key: "previousMarried", label: "Previous Married" },
      { key: "previousMaritalStatus", label: "Previous Marital Status" },
      { key: "yearsSinceMarried", label: "Years Since Married" },
      { key: "numberOfChildren", label: "Number of Children" },
      { key: "stateOfBirth", label: "State of Birth" },
      { key: "territorialCitizenship", label: "Territorial Citizenship" },
      { key: "residenceOnVDDay", label: "Residence on V-D Day" },
      { key: "ableToReadOrWrite", label: "Able to Read or Write" },
      { key: "ableToSpeakEnglish", label: "Able to Speak English" },
      { key: "highestGrade", label: "Highest Grade" },
      { key: "priorOccupation", label: "Prior Occupation" },
      { key: "class", label: "Class" },
      { key: "bloodQuantum", label: "Blood Quantum" },
      { key: "readEnglish", label: "Read English" },
      { key: "writeEnglish", label: "Write English" },
      { key: "readOtherLanguage", label: "Read Other Language" },
      { key: "writeOtherLanguage", label: "Write Other Language" },
      { key: "speakOtherLanguage", label: "Speak Other Language" },
      { key: "converseInHawaiian", label: "Converse in Hawaiian" },
      { key: "ownOrRent", label: "Own or Rent" },
      { key: "numberOfRooms", label: "Number of Rooms" },
      { key: "rentOrValueOfHome", label: "Rent or Value of Home" },
    ],
  },
];

export function getCensusTemplate(templateId) {
  return censusTemplates.find((template) => template.id === templateId);
}

export function getTemplateIdForYear(year) {
  return `us-census-${year}`;
}
