export const censusTemplateYears = [
  "1790",
  "1800",
  "1810",
  "1820",
  "1830",
  "1840",
  "1850",
  "1860",
  "1870",
  "1880",
  "1890",
  "1900",
  "1910",
  "1920",
  "1930",
  "1940",
];

export const censusTemplates = [
  {
    id: "us-census-1790",
    year: "1790",
    label: "1790 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1790 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "givenName", label: "Given Name" },
      { key: "surname", label: "Surname" },
      { key: "freeWhiteMales16Plus", label: "Free white males 16+" },
      { key: "freeWhiteMalesUnder16", label: "Free white males under 16" },
      { key: "freeWhiteFemales", label: "Free white females" },
      { key: "allOtherFreePersons", label: "All other free Persons" },
      { key: "slaves", label: "Slaves" },
      { key: "total", label: "TOTAL" },
    ],
  },
  {
    id: "us-census-1800",
    year: "1800",
    label: "1800 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1800 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "freeWhiteMalesUnder10", label: "Free White Persons - Males Under 10" },
      { key: "freeWhiteMales10To15", label: "Free White Persons - Males 10 to 15" },
      { key: "freeWhiteMales16To25", label: "Free White Persons - Males 16 to 25" },
      { key: "freeWhiteMales26To44", label: "Free White Persons - Males 26 to 44" },
      { key: "freeWhiteMalesOver45", label: "Free White Persons - Males Over 45" },
      { key: "freeWhiteFemalesUnder10", label: "Free White Persons - Females Under 10" },
      { key: "freeWhiteFemales10To15", label: "Free White Persons - Females 10 to 15" },
      { key: "freeWhiteFemales16To25", label: "Free White Persons - Females 16 to 25" },
      { key: "freeWhiteFemales26To44", label: "Free White Persons - Females 26 to 44" },
      { key: "freeWhiteFemalesOver45", label: "Free White Persons - Females Over 45" },
      { key: "total", label: "TOTAL" },
    ],
  },
  {
    id: "us-census-1820",
    year: "1820",
    label: "1820 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1820 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "county", label: "County" },
      { key: "state", label: "State" },
      { key: "engagedInAgriculture", label: "# Engaged in Agriculture" },
      { key: "freeWhiteMalesUnder10", label: "Free White Persons - Males Under 10" },
      { key: "freeWhiteMales10To15", label: "Free White Persons - Males 10 to 15" },
      { key: "freeWhiteMales16To25", label: "Free White Persons - Males 16 to 25" },
      { key: "freeWhiteMales26To44", label: "Free White Persons - Males 26 to 44" },
      { key: "freeWhiteMalesOver45", label: "Free White Persons - Males Over 45" },
      { key: "freeWhiteFemalesUnder10", label: "Free White Persons - Females Under 10" },
      { key: "freeWhiteFemales10To15", label: "Free White Persons - Females 10 to 15" },
      { key: "freeWhiteFemales16To25", label: "Free White Persons - Females 16 to 25" },
      { key: "freeWhiteFemales26To44", label: "Free White Persons - Females 26 to 44" },
      { key: "freeWhiteFemalesOver45", label: "Free White Persons - Females Over 45" },
    ],
  },
  {
    id: "us-census-1830",
    year: "1830",
    label: "1830 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1830 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "totalFreeWhitePersons", label: "Total Free White Persons" },
      { key: "totalSlaves", label: "Total Slaves" },
      { key: "freeWhiteMalesUnder5", label: "Males Under 5" },
      { key: "freeWhiteMales5To9", label: "Males 5 to under 10" },
      { key: "freeWhiteMales10To14", label: "Males 10 to under 15" },
      { key: "freeWhiteMales15To19", label: "Males 15 to under 20" },
      { key: "freeWhiteMales20To29", label: "Males 20 to under 30" },
      { key: "freeWhiteMales30To39", label: "Males 30 to under 40" },
      { key: "freeWhiteMales40To49", label: "Males 40 to under 50" },
      { key: "freeWhiteMales50To59", label: "Males 50 to under 60" },
      { key: "freeWhiteMales60To69", label: "Males 60 to under 70" },
      { key: "freeWhiteMales70To79", label: "Males 70 to under 80" },
      { key: "freeWhiteMales80To89", label: "Males 80 to under 90" },
      { key: "freeWhiteMales90To99", label: "Males 90 to under 100" },
      { key: "freeWhiteMales100Plus", label: "Males 100+" },
      { key: "freeWhiteFemalesUnder5", label: "Females Under 5" },
      { key: "freeWhiteFemales5To9", label: "Females 5 to under 10" },
      { key: "freeWhiteFemales10To14", label: "Females 10 to under 15" },
      { key: "freeWhiteFemales15To19", label: "Females 15 to under 20" },
      { key: "freeWhiteFemales20To29", label: "Females 20 to under 30" },
      { key: "freeWhiteFemales30To39", label: "Females 30 to under 40" },
      { key: "freeWhiteFemales40To49", label: "Females 40 to under 50" },
      { key: "freeWhiteFemales50To59", label: "Females 50 to under 60" },
      { key: "freeWhiteFemales60To69", label: "Females 60 to under 70" },
      { key: "freeWhiteFemales70To79", label: "Females 70 to under 80" },
      { key: "freeWhiteFemales80To89", label: "Females 80 to under 90" },
      { key: "freeWhiteFemales90To99", label: "Females 90 to under 100" },
      { key: "freeWhiteFemales100Plus", label: "Females 100+" },
      { key: "slaveFemalesUnder5", label: "Slaves - Female Under 5" },
      { key: "slaveFemales5To9", label: "Slaves - Female 5 to under 10" },
      { key: "slaveFemales10To14", label: "Slaves - Female 10 to under 15" },
      { key: "slaveFemales15To19", label: "Slaves - Female 15 to under 20" },
      { key: "slaveFemales20To29", label: "Slaves - Female 20 to under 30" },
      { key: "slaveFemales30To39", label: "Slaves - Female 30 to under 40" },
      { key: "slaveFemales40To49", label: "Slaves - Female 40 to under 50" },
      { key: "slaveFemales50To59", label: "Slaves - Female 50 to under 60" },
      { key: "slaveFemales60To69", label: "Slaves - Female 60 to under 70" },
      { key: "slaveFemales70To79", label: "Slaves - Female 70 to under 80" },
      { key: "slaveFemales80To89", label: "Slaves - Female 80 to under 90" },
      { key: "slaveFemales90To99", label: "Slaves - Female 90 to under 100" },
      { key: "slaveFemales100Plus", label: "Slaves - Female 100+" },
    ],
  },
  {
    id: "us-census-1840",
    year: "1840",
    label: "1840 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1840 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "name", label: "Name" },
      { key: "age", label: "Age" },
      { key: "city", label: "City" },
      { key: "malesUnder5", label: "Males Under 5" },
      { key: "malesUnder10", label: "Males under 10" },
      { key: "malesUnder15", label: "Males under 15" },
      { key: "malesUnder20", label: "Males under 20" },
      { key: "malesUnder30", label: "Males under 30" },
      { key: "malesUnder40", label: "Males under 40" },
      { key: "malesUnder50", label: "Males under 50" },
      { key: "malesUnder60", label: "Males under 60" },
      { key: "malesUnder70", label: "Males under 70" },
      { key: "malesUnder80", label: "Males under 80" },
      { key: "malesUnder90", label: "Males under 90" },
      { key: "malesUnder100", label: "Males under 100" },
      { key: "males100Plus", label: "Males 100+" },
      { key: "femalesUnder5", label: "Females Under 5" },
      { key: "femalesUnder10", label: "Females under 10" },
      { key: "femalesUnder15", label: "Females under 15" },
      { key: "femalesUnder20", label: "Females under 20" },
      { key: "femalesUnder30", label: "Females under 30" },
      { key: "femalesUnder40", label: "Females under 40" },
      { key: "femalesUnder50", label: "Females under 50" },
      { key: "femalesUnder60", label: "Females under 60" },
      { key: "femalesUnder70", label: "Females under 70" },
      { key: "femalesUnder80", label: "Females under 80" },
      { key: "femalesUnder90", label: "Females under 90" },
      { key: "femalesUnder100", label: "Females under 100" },
      { key: "females100Plus", label: "Females 100+" },
    ],
  },
  {
    id: "us-census-1850",
    year: "1850",
    label: "1850 U.S. Census",
    description: "Spreadsheet-style entry form based on the 1850 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "dwellingNumber", label: "Dwelling Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "age", label: "Age" },
      { key: "birthYear", label: "Birth Year" },
      { key: "gender", label: "Gender" },
      { key: "race", label: "Race" },
      { key: "occupation", label: "Occupation" },
      { key: "industry", label: "Industry" },
      { key: "realEstate", label: "Real Estate" },
      { key: "birthPlace", label: "Birth Place" },
      { key: "marriedWithinTheYear", label: "Married within the Year" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "cannotReadWrite", label: "Cannot Read, Write" },
      { key: "condition", label: "Condition" },
    ],
  },
  {
    id: "us-census-1920",
    year: "1920",
    label: "1920 U.S. Census",
    sourceWorkbook: "/templates/1920.xltx",
    description: "Spreadsheet-style entry form based on the 1920 United States Federal Census fields.",
    columns: [
      { key: "location", label: "Location" },
      { key: "page", label: "Page" },
      { key: "lineNumber", label: "Line Number" },
      { key: "street", label: "Street" },
      { key: "houseNumber", label: "House Number" },
      { key: "familyNumber", label: "Family Number" },
      { key: "surname", label: "Surname" },
      { key: "givenName", label: "Given Name" },
      { key: "relationship", label: "Relationship" },
      { key: "homeOwnedOrRented", label: "Home Owned or Rented" },
      { key: "homeFreeOrMortgaged", label: "Home Free or Mortgaged" },
      { key: "sex", label: "Sex" },
      { key: "race", label: "Race" },
      { key: "age", label: "Age" },
      { key: "estimatedBirthYear", label: "Estimated Birth Year" },
      { key: "maritalStatus", label: "Marital Status" },
      { key: "immigrationYear", label: "Immigration Year" },
      { key: "naturalizationStatus", label: "Naturalization Status" },
      { key: "naturalizationYear", label: "Naturalization Year" },
      { key: "attendedSchool", label: "Attended School" },
      { key: "ableToRead", label: "Able to read" },
      { key: "ableToWrite", label: "Able to Write" },
      { key: "birthplace", label: "Birthplace" },
      { key: "nativeTongue", label: "Native Tongue" },
      { key: "fathersBirthplace", label: "Father's Birthplace" },
      { key: "mothersBirthplace", label: "Mother's Birthplace" },
    ],
  },
];

export function getCensusTemplate(templateId) {
  return censusTemplates.find((template) => template.id === templateId);
}

export function getTemplateIdForYear(year) {
  return `us-census-${year}`;
}
